config/routes.rb
Rails.application.routes.draw do

  # Admin routes
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  namespace :admins do
    resources :suggestions, only: [:index] do
      post :send_message, on: :member
      collection do
        get :new_request
        get :approved
        get :declined
      end
    end

    resources :problems, only: [:index] do
      collection do
        get :new_issues
        get :archived
      end
    end

    resources :users, only: [] do
      collection do
        get :check_email
      end
    end

    resources :dashboard, only: [:index] do
      collection do
        delete :delete_users
        post :send_notifications
      end
    end 
    resources :settings, only: [:index, :update]
    resources :courses, only: [:index, :show, :destroy] do
      member do
        patch :approve
        patch :reject
      end
    end
  end

  devise_scope :admin do
    get 'admins/password/reset', to: 'admins/passwords#reset'
    post 'admins/password/resend', to: 'admins/passwords#resend', as: :resend_admin_reset_password
  end

  root to: proc { [200, {}, ['Welcome to Playlync API!']] }
  get "/test", to: 'test#show'
  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      
      resources :registrations, only: [:show, :update, :destroy] do
        collection do
          post :forgot_password
          post :otp_verification
          post :reset_password
          post :resend_otp
        end
      end
      
      post '/auth/signup', to: 'registrations#create'
      post '/auth/login', to: 'sessions#login'
      put '/auth/logout', to: 'sessions#logout'
      post '/auth/social_login', to: 'social_logins#social_login'
      get 'alerts', to: 'tee_times#alerts'

      resources :issues, only: [:create]
      resources :tee_times, only: [:index]
      resources :courses, only: [:index, :create]
      resources :profiles, only: [:show, :update, :destroy]
      resources :requests, only: [:create, :index, :destroy]
      post '/search', to: 'requests#search'
      post '/location/courses', to: 'requests#location_courses'
    end
  end
end

app/controllers/admins/settings_controller.rb
class Admins::SettingsController < Admins::BaseController

  def index
  end

  def update
    @admin = current_admin

    if password_fields_present?
      if @admin.valid_password?(params[:admin][:current_password])
        if @admin.update(admin_params)
          bypass_sign_in(@admin)
          flash[:notice] = 'Password updated successfully.'
          redirect_to admins_dashboard_index_path
        else
          flash[:alert] = @admin.errors.full_messages.join(', ')
          render :index
        end
      else
        flash[:alert] = 'Current password is incorrect.'
        render :index
      end
    else
      if @admin.update(admin_params.except(:password, :password_confirmation))
        flash[:notice] =  'Informations updated successfully.'
        redirect_to admins_dashboard_index_path
      else
        flash[:alert] = @admin.errors.full_messages.join(', ')
        render :index
      end
    end
  end

  private

  def admin_params
    params.require(:admin).permit(:full_name, :email, :password, :password_confirmation)
  end

  def password_fields_present?
    params[:admin][:password].present? || params[:admin][:password_confirmation].present?
  end
end

app/views/admins/settings/index.html.erb
<div class="p-5">
  <div class="mb-4 border-b border-gray-200 dark:border-gray-700 w-fit">
    <ul class="flex flex-wrap -mb-px text-sm font-medium text-center" id="default-styled-tab" data-tabs-toggle="#default-styled-tab-content" data-tabs-active-classes="text-sm font-semibold !text-primary hover:text-purple-600 dark:text-purple-500 dark:hover:text-purple-500 !border-primary dark:border-purple-500" data-tabs-inactive-classes="dark:border-transparent !text-secondary hover:text-gray-600 dark:text-gray-400 border-gray-100 !hover:border-primary dark:border-gray-700 dark:hover:text-gray-300" role="tablist">
      <li class="mr-1" role="presentation">
        <button class="inline-block p-4 border-b-[3px] rounded-t-lg" id="Personaldata-styled-tab" data-tabs-target="#styled-Personaldata" type="button" role="tab" aria-controls="Personaldata" aria-selected="false">Personal data</button>
      </li>
      <li class="mr-1" role="presentation">
        <button class="inline-block p-4 border-b-[3px] rounded-t-lg" id="password-styled-tab" data-tabs-target="#styled-password" type="button" role="tab" aria-controls="password" aria-selected="false">Password</button>
      </li>
    </ul>
  </div>
  <div id="default-styled-tab-content">
    <div class="hidden bg-white" id="styled-Personaldata" role="tabpanel" aria-labelledby="Personaldata-tab">
      <div class="w-full max-w-[580px]">
        <p class="text-black text-lg font-semibold">Personal data</p>
        <p class="text-secondary font-normal text-sm mt-3">You can change your data</p>
        <%= form_with(model: current_admin, url: admins_setting_path(current_admin), method: :put, local: true) do |form| %>
          <div class="flex justify-between sm:items-center max-sm:flex-col gap-1 mt-3 lg:mt-6">
            <label class="text-sm font-medium text-typo">Full Name</label>
            <%= form.text_field :full_name, class: "border border-gray-2 hover:border-primary focus:ring-0 bg-gray-3 rounded-md !outline-none text-sm block w-full sm:max-w-[380px] px-3 py-3", placeholder: "enter full name", required: true %>
          </div>
          <div class="flex justify-between sm:items-center max-sm:flex-col gap-1 mt-4">
            <label class="text-sm font-medium text-typo">Email</label>
            <%= form.email_field :email, class: "border border-gray-2 hover:border-primary focus:ring-0 bg-gray-3 rounded-md !outline-none text-sm block w-full sm:max-w-[380px] px-3 py-3", placeholder: "enter your email", required: true %>
          </div>
          <div class="flex gap-3 justify-end mt-4 lg:mt-8">
            <%= link_to 'Cancel', admins_settings_path, class: 'flex items-center justify-center text-secondary w-full max-w-[107px] h-9 border border-gray-2 rounded hover:bg-primary hover:text-white transition-all' %>
            <%= form.submit "Update Data", class: "w-full max-w-[180px] bg-primary hover:opacity-80 rounded h-9 text-white transition-all cursor-pointer" %>
          </div>
        <% end %>
      </div>
    </div>
    <div class="hidden bg-white" id="styled-password" role="tabpanel" aria-labelledby="password-tab">
      <div class="w-full max-w-[580px]">
        <p class="text-black text-lg font-semibold">Password</p>
        <p class="text-secondary font-normal text-sm mt-3">Please enter your current password to change your password.</p>
        <%= form_with(model: current_admin, url: admins_setting_path(current_admin), method: :put, local: true) do |form| %>
          <div class="flex justify-between sm:items-center max-sm:flex-col gap-1 mt-3 lg:mt-6">
            <label class="text-sm font-medium text-typo">Current Password</label>
            <div class="relative w-full sm:max-w-[380px]">
              <%= form.password_field :current_password, class: "password-field tracking-widest border border-gray-2 hover:border-primary bg-gray-3 rounded !outline-none text-sm focus:!ring-0 block w-full px-3 py-3", placeholder: "", required: true %>
              <div class="cursor-pointer absolute top-4 right-3.5">
                <%= image_tag '/assets/svg/Eye-icon.svg', alt: '', class: 'toggle-password size-4', id: 'togglePassword2' %>
              </div>
            </div>
          </div>
          <div class="flex justify-between sm:items-center max-sm:flex-col gap-1 mt-4">
            <label class="text-sm font-medium text-typo">New Password</label>
            <div class="relative w-full sm:max-w-[380px]">
              <%= form.password_field :password, class: "password-field tracking-widest border border-gray-2 hover:border-primary bg-gray-3 rounded !outline-none text-sm focus:!ring-0 block w-full px-3 py-3", placeholder: "", required: true %>
              <div class="cursor-pointer absolute top-4 right-3.5">
                <%= image_tag '/assets/svg/Eye-icon.svg', alt: '', class: 'toggle-password size-4', id: 'togglePassword2' %>
              </div>
            </div>
          </div>
          <div class="flex justify-between sm:items-center max-sm:flex-col gap-1 mt-4">
            <label class="text-sm font-medium text-typo">Confirm Password</label>
            <div class="relative w-full sm:max-w-[380px]">
              <%= form.password_field :password_confirmation, class: "password-field tracking-widest border border-gray-2 hover:border-primary bg-gray-3 rounded !outline-none text-sm focus:!ring-0 block w-full px-3 py-3", placeholder: "", required: true %>
              <div class="cursor-pointer absolute top-4 right-3.5">
                <%= image_tag '/assets/svg/Eye-icon.svg', alt: '', class: 'toggle-password size-4', id: 'togglePassword2' %>
              </div>
            </div>
          </div>
          <div class="flex gap-3 justify-end mt-4 lg:mt-8">
            <%= link_to 'Cancel', admins_settings_path, class: 'text-secondary w-full max-w-[107px] flex items-center justify-center h-9 border border-gray-2 rounded hover:bg-primary hover:text-white transition-all' %>
            <%= form.submit "Update Data", class: "w-full max-w-[180px] bg-primary hover:opacity-80 rounded h-9 text-white transition-all cursor-pointer" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>