config/routes.rb
Rails.application.routes.draw do

  # Admin routes
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  namespace :admins do
    resources :suggestions, only: [:index] do
      post :send_message, on: :member
      collection do
        get :new_request
        get :approved
        get :declined
      end
    end

    resources :problems, only: [:index] do
      collection do
        get :new_issues
        get :archived
      end
    end

    resources :users, only: [] do
      collection do
        get :check_email
      end
    end

    resources :dashboard, only: [:index] do
      collection do
        delete :delete_users
        post :send_notifications
      end
    end 
    resources :settings, only: [:index, :update]
    resources :courses, only: [:index, :show, :destroy] do
      member do
        patch :approve
        patch :reject
      end
    end
  end

  devise_scope :admin do
    get 'admins/password/reset', to: 'admins/passwords#reset'
    post 'admins/password/resend', to: 'admins/passwords#resend', as: :resend_admin_reset_password
  end

  root to: proc { [200, {}, ['Welcome to Playlync API!']] }
  get "/test", to: 'test#show'
  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      
      resources :registrations, only: [:show, :update, :destroy] do
        collection do
          post :forgot_password
          post :otp_verification
          post :reset_password
          post :resend_otp
        end
      end
      
      post '/auth/signup', to: 'registrations#create'
      post '/auth/login', to: 'sessions#login'
      put '/auth/logout', to: 'sessions#logout'
      post '/auth/social_login', to: 'social_logins#social_login'
      get 'alerts', to: 'tee_times#alerts'

      resources :issues, only: [:create]
      resources :tee_times, only: [:index]
      resources :courses, only: [:index, :create]
      resources :profiles, only: [:show, :update, :destroy]
      resources :requests, only: [:create, :index, :destroy]
      post '/search', to: 'requests#search'
      post '/location/courses', to: 'requests#location_courses'
    end
  end
end

app/controllers/admins/problems_controller.rb
class Admins::ProblemsController < Admins::BaseController
  def new_issues
    @new_issues = Issue.new_issues
  end

  def archived
    @archived_issues = Issue.archived_issues
  end
end

app/views/admins/problems/archived.html.erb
<div class="p-3 sm:p-5">
  <div class="">
    <div class="mb-6 max-w-[240px] w-full">
      <ul class="flex text-sm font-semibold text-center" id="default-tab" data-tabs-toggle="#default-tab-content" role="tablist" data-tabs-toggle="#default-styled-tab-content" data-tabs-active-classes="text-sm font-semibold !text-primary hover:text-purple-600 dark:text-purple-500 dark:hover:text-purple-500 !border-primary dark:border-purple-500" data-tabs-inactive-classes="dark:border-transparent !text-secondary hover:text-gray-600 dark:text-gray-400 border-gray-100 !hover:border-primary dark:border-gray-700 dark:hover:text-gray-300">
  
        <li class="me-2" role="presentation">
          <%= link_to 'Suggestions', new_request_admins_suggestions_path, class: 'inline-block p-4 border-b-[3px] rounded-t-lg text-secondary hover:!text-secondary' %>
        </li>

        <li class="me-2" role="presentation">
          <%= link_to 'Problems', new_issues_admins_problems_path, class: 'inline-block p-4 border-b-[3px] rounded-t-lg', role: 'tab', id: 'Problems-tab', data: { tabs_target: '#Problems', toggle: 'tab' }, aria: { controls: 'Problems', selected: 'false' } %>
        </li>
      </ul>
    </div>
    <div id="default-tab-content">
      <div id="Suggestions" role="tabpanel" aria-labelledby="Suggestions-tab">
        <div class="mb-3 px-3 py-2 bg-[#F6F6F6] rounded-md w-full">
          <ul class="flex gap-4 text-xs font-semibold text-center" id="inner-tab" data-tabs-toggle="#inner-tab-content" role="tablist">
            <li class="" role="presentation">
              <%= link_to 'New', new_issues_admins_problems_path, class: 'inline-block text-secondary hover:!text-secondary aria-selected:!text-black', role: 'tab' %>
            </li>
            <li class="" role="presentation">
              <%= link_to 'Archived', archived_admins_problems_path, class: 'inline-block', role: 'tab' %>

            </li>
          </ul>
        </div>
      </div>

      <div id="Archived" role="tabpanel" aria-labelledby="archived-tab">
        <div class="overflow-x-auto scrollbar">
            <table class="min-w-full bg-white">
            <thead class="bg-[#E8F6FF]">
                <tr>
                <th class="text-left p-3 text-black text-sm font-medium rounded-l-md">E-mail</th>
                <th class="text-left p-3 text-black text-sm font-medium">Topic</th>
                <th class="text-left p-3 text-black text-sm font-medium">Description</th>
                <th class="text-left p-3 text-black text-sm font-medium rounded-r-md">Actions</th>
                </tr>
            </thead>
            <tbody class="text-sm font-normal text-typo">
                <% @archived_issues.each do |issue| %>
                <tr class="border-b border-gray-2">
                    <td class="whitespace-nowrap py-4 px-3"><%= issue.email%>
                    </td>
                    <td class="whitespace-nowrap py-4 px-3"><%= issue.subject%>
                    </td>
                    <td class="py-4 px-3">
                    <p class="line-clamp-1 max-w-[600px] w-full">
                        <%= issue.body%>
                    </p>
                    </td>
                    <td class="py-4 px-3 flex items-center gap-3">
                    <div class="size-6">
                        <button type="button" data-modal-target="popup-modalarchived-<%= issue.id %>" data-modal-toggle="popup-modalarchived-<%= issue.id %>" class="size-6 cursor-pointer">
                        <%= image_tag '/assets/svg/mdi_eye.svg', alt: '', class: '' %>
                        </button>
                        <div id="popup-modalarchived-<%= issue.id %>" tabindex="-1" class="fixed hidden bg-black px-5 md:px-0 bg-opacity-50 inset-0 justify-center items-center z-50">
                        <div class="w-full max-w-[550px] h-fit relative mx-auto bg-white rounded shadow-[0px_0px_12px_0px_#0000001F]">
                            <div class="px-4 md:px-12 py-5">
                            <div class="flex justify-between items-center mb-8">
                                <h1 class="text-xl font-medium">View problem</h1>
                                <div data-modal-hide="popup-modalarchived-<%= issue.id %>" class="bg-transparent hover:bg-gray-200 rounded-lg p-1.5 cursor-pointer">
                                <%= image_tag '/assets/svg/close.svg', alt: '', class: 'size-6' %>
                                </div>
                            </div>
                            <div class="flex flex-col gap-y-4 mb-4 lg:mb-8">
                                <div class="w-full">
                                <label class="text-sm font-medium text-primary mb-2">E-mail</label>
                                <div class="border border-gray-2 mt-2 rounded text-sm font-normal text-black block w-full px-3 py-2">
                                    <%= issue.email %>
                                </div>
                                </div>
                                <div class="w-full">
                                <label class="text-sm font-medium text-primary mb-2">Topic</label>
                                <div class="border border-gray-2 mt-2 rounded text-sm font-normal text-black block w-full px-3 py-2">
                                    <%= issue.subject %>
                                </div>
                                </div>
                                <div class="w-full">
                                <label class="text-sm font-medium text-primary mb-2">Description</label>
                                <div class="line-clamp-6 whitespace-normal min-h-20 border border-gray-2 break-all mt-2 rounded text-sm font-normal text-typo block w-full px-3 py-2">
                                    <%= issue.body %>
                                </div>
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    <div class="size-6">
                        <button type="button" data-modal-target="popup-modalarchived2-<%= issue.id %>" data-modal-toggle="popup-modalarchived2-<%= issue.id %>" class="size-6 cursor-pointer">
                        <%= image_tag '/assets/svg/mail.svg', alt: '', class: '' %>
                        </button>
                        <div id="popup-modalarchived2-<%= issue.id %>" tabindex="-1" class="fixed hidden bg-black px-5 md:px-0 bg-opacity-50 inset-0 justify-center items-center z-50">
                        <div class="w-full max-w-[550px] relative mx-auto bg-white rounded shadow-[0px_0px_12px_0px_#0000001F]">
                            <div class="px-4 md:px-12 py-5">
                            <div class="flex justify-between items-center mb-8">
                                <h1 class="text-xl font-medium">Send a message</h1>
                                <div data-modal-hide="popup-modalarchived2-<%= issue.id %>" class="bg-transparent hover:bg-gray-200 rounded-lg p-1.5 cursor-pointer">
                                <%= image_tag '/assets/svg/close.svg', alt: '', class: 'size-6' %>
                                </div>
                            </div>
                            <%= form_with url: send_message_admins_suggestion_path(issue), method: :post, local: true do |f| %>
                                <div class="flex flex-col gap-y-4 mb-4 lg:mb-8">
                                <div class="w-full">
                                    <label class="text-sm font-medium text-primary mb-2">E-mail</label>
                                    <%= f.email_field :email, value: issue.email, class: 'border border-gray-2 mt-2 rounded text-sm font-normal text-black block w-full px-3 py-2 focus:!ring-0', required: true, readonly: true %>
                                </div>
                                <div class="w-full">
                                    <label class="text-sm font-medium text-primary mb-2">Message</label>
                                    <%= f.text_area :message, rows: 3, class: 'border border-gray-2 hover:border-primary resize-none mt-2 rounded text-sm font-normal text-black block w-full px-3 py-2 placeholder:text-secondary focus:outline-transparent focus:ring-0 !outline-none', placeholder: 'Enter your text' , required: true %>
                                </div>
                                </div>
                                <div class="flex justify-end">
                                <%= f.submit 'Send a message', data: { modal_hide: "popup-modal3-#{issue.id}" }, class: 'cursor-pointer w-40 h-[34px] flex text-xs font-normal rounded justify-center items-center bg-primary text-white hover:opacity-80' %>
                                </div>
                            <% end %>
                            </div>
                        </div>
                        </div>
                    </div>
                    </td>
                </tr>
                <% end %>
            </tbody>
            </table>
        </div>
        </div>
    </div>
  </div>
</div>

app/views/admins/problems/new_issues.html.erb
<div class="p-3 sm:p-5">
  <div class="">
    <div class="mb-6 max-w-[240px] w-full">
      <ul class="flex text-sm font-semibold text-center" id="default-tab" data-tabs-toggle="#default-tab-content" role="tablist" data-tabs-toggle="#default-styled-tab-content" data-tabs-active-classes="text-sm font-semibold !text-primary hover:text-purple-600 dark:text-purple-500 dark:hover:text-purple-500 !border-primary dark:border-purple-500" data-tabs-inactive-classes="dark:border-transparent !text-secondary hover:text-gray-600 dark:text-gray-400 border-gray-100 !hover:border-primary dark:border-gray-700 dark:hover:text-gray-300">
  
        <li class="me-2" role="presentation">
          <%= link_to 'Suggestions', new_request_admins_suggestions_path, class: 'inline-block p-4 border-b-[3px] rounded-t-lg text-secondary hover:!text-secondary' %>
        </li>

        <li class="me-2" role="presentation">
          <%= link_to 'Problems', new_issues_admins_problems_path, class: 'inline-block p-4 border-b-[3px] rounded-t-lg', role: 'tab', id: 'Problems-tab', data: { tabs_target: '#Problems', toggle: 'tab' }, aria: { controls: 'Problems', selected: 'false' } %>
        </li>
      </ul>
    </div>
    <div id="default-tab-content">
      <div id="Suggestions" role="tabpanel" aria-labelledby="Suggestions-tab">
        <div class="mb-3 px-3 py-2 bg-[#F6F6F6] rounded-md w-full">
           <ul class="flex gap-4 text-xs font-semibold text-center" id="inner-tab" data-tabs-toggle="#inner-tab-content" role="tablist">
            <li class="" role="presentation">
              <%= link_to 'New', new_issues_admins_problems_path, class: 'inline-block', role: 'tab' %>
            </li>
            <li class="" role="presentation">
              <%= link_to 'Archived', archived_admins_problems_path, class: 'inline-block text-secondary hover:!text-secondary aria-selected:!text-black', role: 'tab' %>

            </li>
          </ul>
        </div>
      </div>

      <div id="New" role="tabpanel" aria-labelledby="New-tab">
        <div class="overflow-x-auto scrollbar">
          <table class="min-w-full bg-white">
            <thead class="bg-[#E8F6FF]">
              <tr>
                <th class="text-left p-3 text-black text-sm font-medium rounded-l-md">E-mail</th>
                <th class="text-left p-3 text-black text-sm font-medium">Topic</th>
                <th class="text-left p-3 text-black text-sm font-medium min-w-[250px]">Description</th>
                <th class="text-left p-3 text-black text-sm font-medium rounded-r-md">Actions</th>
              </tr>
            </thead>
            <tbody class="text-sm font-normal text-typo">
                <% @new_issues.each do |issue| %>
                <tr class="border-b border-gray-2">
                    <td class="whitespace-nowrap py-4 px-3"><%= issue.email %></td>
                    <td class="whitespace-nowrap py-4 px-3"><%= issue.subject %></td>
                    <td class="py-4 px-3">
                    <p class="line-clamp-1 max-w-[600px] w-full">
                        <%= issue.body %>
                    </p>
                    </td>
                    <td class="py-4 px-3 flex items-center gap-3">
                    <button type="button" data-modal-target="popup-modal<%= issue.id %>" data-modal-toggle="popup-modal<%= issue.id %>" class="size-6 cursor-pointer">
                        <%= image_tag '/assets/svg/mdi_eye.svg', alt: '', class: '' %>
                    </button>
                    <div id="popup-modal<%= issue.id %>" tabindex="-1" class="fixed hidden bg-black px-5 md:px-0 bg-opacity-50 inset-0 justify-center items-center z-50">
                        <div class="w-full max-w-[550px] h-fit relative mx-auto bg-white rounded shadow-[0px_0px_12px_0px_#0000001F]">
                        <div class="px-4 md:px-12 py-5">
                            <div class="flex justify-between items-center mb-8">
                            <h1 class="text-xl font-medium">View problem</h1>
                            <div data-modal-hide="popup-modal<%= issue.id %>" class="bg-transparent hover:bg-gray-200 rounded-lg p-1.5 cursor-pointer">
                                <%= image_tag '/assets/svg/close.svg', alt: '', class: 'size-6' %>
                            </div>
                            </div>
                            <div class="flex flex-col gap-y-4 mb-4 lg:mb-8">
                            <div class="w-full">
                                <label class="text-sm font-medium text-primary mb-2">E-mail</label>
                                <div class="border border-gray-2 mt-2 rounded text-sm font-normal text-black block w-full px-3 py-2">
                                <%= issue.email %>
                                </div>
                            </div>
                            <div class="w-full">
                                <label class="text-sm font-medium text-primary mb-2">Topic</label>
                                <div class="border border-gray-2 mt-2 rounded text-sm font-normal text-black block w-full px-3 py-2">
                                <%= issue.subject %>
                                </div>
                            </div>
                            <div class="w-full">
                                <label class="text-sm font-medium text-primary mb-2">Description</label>
                                <div class="line-clamp-6 whitespace-normal min-h-20 border border-gray-2 break-all mt-2 rounded text-sm font-normal text-typo block w-full px-3 py-2">
                                <%= issue.body %>
                                </div>
                            </div>
                            </div>
                        </div>
                        </div>
                    </div>
                    <button type="button" data-modal-target="popup-modal3-<%= issue.id %>" data-modal-toggle="popup-modal3-<%= issue.id %>" class="size-6 cursor-pointer">
                        <%= image_tag '/assets/svg/mail.svg', alt: '', class: '' %>
                    </button>
                    <div id="popup-modal3-<%= issue.id %>" tabindex="-1" class="fixed hidden bg-black px-5 md:px-0 bg-opacity-50 inset-0 justify-center items-center z-50">
                        <div class="w-full max-w-[550px] relative mx-auto bg-white rounded shadow-[0px_0px_12px_0px_#0000001F]">
                            <div class="px-4 md:px-12 py-5">
                            <div class="flex justify-between items-center mb-8">
                                <h1 class="text-xl font-medium">Send a message</h1>
                                <div data-modal-hide="popup-modal3-<%= issue.id %>" class="bg-transparent hover:bg-gray-200 rounded-lg p-1.5 cursor-pointer">
                                <%= image_tag '/assets/svg/close.svg', alt: '', class: 'size-6' %>
                                </div>
                            </div>
                            <%= form_with url: send_message_admins_suggestion_path(issue), method: :post, local: true do |f| %>
                                <div class="flex flex-col gap-y-4 mb-4 lg:mb-8">
                                <div class="w-full">
                                    <label class="text-sm font-medium text-primary mb-2">E-mail</label>
                                    <%= f.email_field :email, value: issue.email, class: 'border border-gray-2 mt-2 rounded text-sm font-normal text-black block w-full px-3 py-2 focus:!ring-0' %>
                                </div>
                                <div class="w-full">
                                    <label class="text-sm font-medium text-primary mb-2">Message</label>
                                    <%= f.text_area :message, rows: 3, class: 'border border-gray-2 hover:border-primary resize-none mt-2 rounded text-sm font-normal text-black block w-full px-3 py-2 placeholder:text-secondary focus:outline-transparent focus:ring-0 !outline-none', placeholder: 'Enter your text' %>
                                </div>
                                </div>
                                <div class="flex justify-end">
                                <%= f.submit 'Send a message', data: { modal_hide: "popup-modal3-#{issue.id}" }, class: 'cursor-pointer w-40 h-[34px] flex text-xs font-normal rounded justify-center items-center bg-primary text-white hover:opacity-80' %>
                                </div>
                            <% end %>
                            </div>
                        </div>
                        </div>

                    </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>