config/routes.rb
Rails.application.routes.draw do

  # Admin routes
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    passwords: 'admins/passwords'
  }

  namespace :admins do
    resources :suggestions, only: [:index] do
      post :send_message, on: :member
      collection do
        get :new_request
        get :approved
        get :declined
      end
    end

    resources :problems, only: [:index] do
      collection do
        get :new_issues
        get :archived
      end
    end

    resources :users, only: [] do
      collection do
        get :check_email
      end
    end

    resources :dashboard, only: [:index] do
      collection do
        delete :delete_users
        post :send_notifications
      end
    end 
    resources :settings, only: [:index, :update]
    resources :courses, only: [:index, :show, :destroy] do
      member do
        patch :approve
        patch :reject
      end
    end
  end

  devise_scope :admin do
    get 'admins/password/reset', to: 'admins/passwords#reset'
    post 'admins/password/resend', to: 'admins/passwords#resend', as: :resend_admin_reset_password
  end

  root to: proc { [200, {}, ['Welcome to Playlync API!']] }
  get "/test", to: 'test#show'
  namespace :api, constraints: { format: 'json' } do
    namespace :v1 do
      
      resources :registrations, only: [:show, :update, :destroy] do
        collection do
          post :forgot_password
          post :otp_verification
          post :reset_password
          post :resend_otp
        end
      end
      
      post '/auth/signup', to: 'registrations#create'
      post '/auth/login', to: 'sessions#login'
      put '/auth/logout', to: 'sessions#logout'
      post '/auth/social_login', to: 'social_logins#social_login'
      get 'alerts', to: 'tee_times#alerts'

      resources :issues, only: [:create]
      resources :tee_times, only: [:index]
      resources :courses, only: [:index, :create]
      resources :profiles, only: [:show, :update, :destroy]
      resources :requests, only: [:create, :index, :destroy]
      post '/search', to: 'requests#search'
      post '/location/courses', to: 'requests#location_courses'
    end
  end
end

app/views/layouts/_header.html.erb
<header class="flex justify-between gap-4 item-center px-5 py-4 bg-gray-3 w-full border-b border-gray-2">
  <div class="flex gap-2 items-center">
    <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar" type="button" class="inline-flex items-center p-2 text-sm text-gray-500 rounded-lg md:hidden hover:bg-gray-200 transition-all">
      <%= image_tag '/assets/svg/hamburg.svg', alt: '', class: 'size-6' %>
    </button>
    <h3 class="text-lg font-medium text-black">
      <% header_title = case controller_name %>
    <% when "dashboard" %>
      Admin Panel
    <% when "courses" %>
      Golf courses
    <% when "suggestions" %>
      Suggestions and Problems
    <% when "settings" %>
      Settings
    <% end %>
  </h3>
</div>
<div class="flex items-center gap-1">
  <div class="flex items-center">
    <button type="button" class="flex items-center text-sm font-medium text-black hover:bg-gray-200 rounded p-2" aria-expanded="false" id="dropdownInformationButton" data-dropdown-toggle="dropdownInformation">
      Admin
      <%= image_tag '/assets/svg/arrowdown.svg', alt: '', class: 'ml-1' %>
    </button>
    <div id="dropdownInformation" class="z-10 hidden bg-white max-w-[140px] w-full rounded shadow-btn !-ml-8">
      <ul class="" aria-labelledby="dropdownInformationButton">
        <li class="text-[10px] font-semibold text-black border-b border-gray-5 px-3 pt-2 pb-0.5">
          Admin
        </li>
        <li class="px-3 pt-0.5 pb-2 text-[11px] block font-normal text-black border-b border-gray-5 break-words">
          <%= current_admin.full_name %>
          <span class="text-[10px] text-secondary text-normal mt-0.5"><%=current_admin.email %></span>
        </li>
      </ul>
      <div class="">
        <%= button_to "Log out", destroy_admin_session_path, :method => 'delete', data:{turbo: "false"}, class: "block w-full py-2 px-3 text-xs font-normal text-[#FD3430] hover:bg-[#FD3430]/10 text-left transition-all" %>
      </div>
    </div>
  </div>
  <div class="size-8 overflow-hidden rounded-full bg-sky-blue text-center">
    <%= image_tag '/assets/svg/avatar.svg', alt: '', class: 'w-full' %>
  </div>
</div>
</header>

app/views/layouts/_sidebar.html.erb
<aside id="logo-sidebar" class="fixed top-0 left-0 z-40 w-[220px] h-screen transition-transform duration-300 -translate-x-full md:!translate-x-0" aria-label="Sidebar">
  <div class="h-full scrollbar overflow-y-auto bg-sky-blue relative">
      <button data-drawer-target="logo-sidebar" data-drawer-toggle="logo-sidebar" aria-controls="logo-sidebar" type="button" class="hover:bg-gray-200 transition-all absolute top-2 right-2.5 inline-flex items-center p-1 text-sm text-gray-500 rounded-lg md:hidden">
    <%= image_tag '/assets/svg/close.svg', alt: '', class: 'size-6' %>
  </button>
    <div class="pt-8 pb-14 mx-auto">
      <%= link_to image_tag('/assets/svg/Logo.svg', alt: '', class: 'mx-auto w-[100px] h-[72px]'), admins_dashboard_index_path %>
    </div>
    <ul class="space-y-2">
      <li class="">
        <%= link_to admins_dashboard_index_path, class: "flex gap-4 items-center px-4 py-2 text-sm font-medium text-black/40 hover:bg-white/40 hover:text-dark-blue transition-all #{active_tab_class(admins_dashboard_index_path)}" do %>
          <%= image_tag '/assets/svg/admin.svg', alt: '', class: 'size-5' %>
          Admin Panel
        <% end %>
      </li>
      <li class="">
        <%= link_to admins_courses_path, class: "flex gap-4 items-center px-4 py-2 text-sm font-medium text-black/40 hover:bg-white/40 hover:text-dark-blue transition-all #{active_tab_class(admins_courses_path)}" do %>
          <%= image_tag '/assets/svg/golf.svg', alt: '', class: 'size-5' %>
          Golf courses
        <% end %>
      </li>
      <li class="">
        <%= link_to new_request_admins_suggestions_path, class: " flex gap-4 items-center px-4 py-2 text-sm font-medium text-black/40 hover:bg-white/40 hover:text-dark-blue transition-all #{active_tab_class(new_request_admins_suggestions_path)} #{active_tab_class(new_issues_admins_problems_path)} #{active_tab_class(approved_admins_suggestions_path)} #{active_tab_class(declined_admins_suggestions_path)} #{active_tab_class(new_issues_admins_problems_path)} #{active_tab_class(archived_admins_problems_path)}" do %>
          <%= image_tag '/assets/svg/suggest.svg', alt: '', class: 'size-5' %>
          Suggestions and problems
        <% end %>
      </li>
      <li class="">
        <%= link_to admins_settings_path, class: " flex gap-4 items-center px-4 py-2 text-sm font-medium text-black/40 hover:bg-white/40 hover:text-dark-blue transition-all #{active_tab_class(admins_settings_path)}" do %>
          <%= image_tag '/assets/svg/setting.svg', alt: '', class: 'size-5' %>
          Settings
        <% end %>
      </li>
    </ul>
  </div>
</aside>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayLync</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.css" %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_include_tag "https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js" %>
    <link rel="icon" href="<%= asset_path('favicon.ico') %>" type="image/x-icon">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700&display=swap">
  </head>
  <body class="bg-white">
    <!-- Flash Messages -->
    <% if flash[:notice] %>
      <div id="notice" class="absolute bottom-4 right-8 bg-green-100 text-green-700 px-4 py-2 rounded mb-4 w-full max-w-[400px]">
        <span><%= flash[:notice] %></span>
        <button class="absolute top-1 right-2 text-xl font-bold text-green-700" onclick="this.parentElement.style.display='none'">&times;</button>
        <!-- Progress bar container -->
        <div class="flash-progress-bar">
          <div class="flash-progress-success"></div>
        </div>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div id="alert" class="absolute bottom-4 right-8 bg-red-100 text-red-700 px-4 py-2 rounded mb-4 w-full max-w-[400px]">
        <span><%= flash[:alert] %></span>
        <button class="absolute top-1 right-2 text-xl font-bold text-red-700" onclick="this.parentElement.style.display='none'">&times;</button>
        <!-- Progress bar container -->
        <div class="flash-progress-bar">
          <div class="flash-progress-error"></div>
        </div>
      </div>
    <% end %>

    <% if %w[dashboard courses settings suggestions problems].include?(controller_name) %>
      <%= render 'layouts/sidebar' %>
      <main class="ml-0 md:!ml-[220px] bg-white">
        <%= render 'layouts/header' %>
      <% end %>
      <%= yield %>
    </main>

    <script>
      setTimeout(function() {
        var notice = document.getElementById('notice');
        var alert = document.getElementById('alert');
        if (notice) {
          notice.style.display = 'none';
        }
        if (alert) {
          alert.style.display = 'none';
        }
      }, 4000);
    </script>
  </body>
</html>